variable "COMPONENT"        {}
variable "ENV"              {}
variable "INSTANCE_TYPE"    {}
variable "bucket"           {}
variable "region"           {}
variable "PORT"             {}
variable "HEALTH"           {}
variable "APP_ARTIFACT_VERSION" {}
variable "ASG_LOAD_AVERAGE" {}
variable "ASG_MAX_INSTANCES" {}